# General
title: "HMC Code"
tagline: "Source code and architecture!!"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# Gems
gems: [jekyll-paginate]
paginate: 5
permalink: /:year-:month-:day/:title

# Social share and comments.
# disqus-id: yourusername
# twitter: yourusername
# github: yourusername
# google: +yourusername

# RSS feed
# rss-feed-limit: 10
# rss-show-full: "no"
